dist: bionic
sudo: false
language: elixir
elixir:
  - 1.11.3
  - 1.11.2
  - 1.11.1
  - 1.11.0
  - 1.10.4
  - 1.10.3
  - 1.10.2
  - 1.10.1
  - 1.10.0
otp_release:
  - 23.2
  - 23.1
  - 23.0
  - 22.2
  - 22.1
  - 22.0
before_script: git submodule update --init
matrix:
  include:
    - install:
        - mix local.rebar --force
        - mix local.hex --force
      script:
        - mix format --check-formatted --dry-run
        - mix credo --strict
    - secure: fpg2leA+GSEcbW+B9lkUPFHAsPoiq9VIF48izB4anR65TZgPIHoy7W04Ly+cHSDuPYPxxtCuZW5YU5ZBi3GAXNLsKZG3uTaoLQj+atZsDdyZNW7Z7Df2uVm3eIK7wC7XojalNtShYx56xTC19xrH01n6VouAcbgJ3TIfxQCraDk=
      script: mix coveralls.travis
